<?php
$Courses = array(
    array("nom"=>"HTML","img"=>"../images/html-5.png","desc"=>"HyperText Markup Language is the most basic building block of the Web. It defines the meaning and structure of web content. Other technologies besides HTML are generally used to describe a web page's appearance (CSS) or functionality (JavaScript)"),
    array("nom"=>"CSS","img"=>"../images/css-3.png","desc"=>"Cascading Style Sheets is used to style and layout web pages — for example, to alter the font, color, size, and spacing of your content, split it into multiple columns, or add animations and other decorative features"),
    array("nom"=>"JavaScript","img"=>"../images/js.png","desc"=>" Dynamic programming language that's used for web development, in web applications, for game development, and lots more. It allows you to implement dynamic features on web pages that cannot be done with only HTML and CSS"),
    array("nom"=>"PHP","img"=>"../images/php.png","desc"=>"Script language and interpreter that is freely available and used primarily on Linux Web servers. PHP, originally derived from Personal Home Page Tools, now stands for PHP: Hypertext Preprocessor, which the PHP FAQ describes as a recursive acronym"),
    array("nom"=>"REACT","img"=>"../images/react.png","desc"=>"React. js, more commonly known as React, is a free, open-source JavaScript library. It works best to build user interfaces by combining sections of code (components) into full websites. Originally built by Facebook, Meta and the open-source community now maintain it"),
    array("nom"=>"C","img"=>"../images/letter-c.png","desc"=>"C is an imperative procedural language supporting structured programming, lexical variable scope, and recursion, It was designed to be compiled to provide low-level access to memory and language constructs that map efficiently to machine instructions"),
    array("nom"=>"C++","img"=>"../images/c-.png","desc"=>"C++ is an object-oriented programming (OOP) language that is viewed by many as the best language for creating large-scale applications. C++ is a superset of the C language. A related programming language, Java, is based on C++ but optimized"),
    array("nom"=>"C#","img"=>"../images/c-sharp.png","desc"=>"C# is an object-oriented programming language from Microsoft that aims to combine the computing power of C++ with the programming ease of Visual Basic. C# is based on C++ and contains features similar to those of Java"),
);
?>